---
- name: Install AWS CLI
  apt:
    name: awscli
    state: present
    update_cache: yes
  become: true

- name: Login to ECR
  shell: aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry_url }}
  become: true
